CREATE DATABASE SQLPSW2
USE SQLPSW2
CREATE TABLE EMPLOYEE(E_NO INT, E_NAME VARCHAR (200) CONSTRAINT CHK_NAME
CHECK (E_NAME NOT LIKE '!' AND E_NAME NOT LIKE '@' AND E_NAME NOT LIKE '#' AND E_NAME NOT LIKE'$'), 
DOB DATETIME,AGE INT CHECK (AGE<200),
ADRESS VARCHAR (1000), COUNTRY VARCHAR (200), 
PINCODE VARCHAR(10),P_NO VARCHAR(20),DEPT VARCHAR(200) )

ALTER TABLE EMPLOYEE ADD CONSTRAINT CHK_PIN CHECK (PINCODE LIKE '%[^A-Z]%')


CREATE TABLE ATTENDENCE ( A_DATE DATETIME, 
EMPNO INT, A_STATUS VARCHAR(200) 
CONSTRAINT CHK_STATUS CHECK(A_STATUS LIKE 'A' OR A_STATUS LIKE 'P'))

SELECT * FROM EMPLOYEES

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 50

SELECT A.FIRST_NAME , A.DEPARTMENT_ID FROM EMPLOYEES A JOIN EMPLOYEES B ON A.DEPARTMENT_ID = B.DEPARTMENT_ID 
SELECT DISTINCT FIRST_NAME,PHONE_NUMBER FROM EMPLOYEES
SELECT DEPARTMENT_ID AS DEPARTMENT , COUNT (1) FROM EMPLOYEES GROUP BY DEPARTMENT_ID 
SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES) 

SELECT * FROM EMPLOYEE
SELECT * FROM ATTENDENCE

INSERT INTO EMPLOYEE VALUES (1,'KIRAN SAI','12-22-1999',23,'HYDERABAD','INDIA','500079',9701926341,'HR')
INSERT INTO EMPLOYEE VALUES (2,'SAI KIRAN','11-22-1999',22,'HYDERABAD','INDIA','500079',9701926342,'TESTING')
INSERT INTO EMPLOYEE VALUES (3,'SOMESH','11-22-1987',32,'RAMACHANDRA','INDIA','500089',9704291,'TOOLANDIEMAKING')
INSERT INTO EMPLOYEE VALUES (4,'KAMESH','11-22-1894',42,'HYSDERABAD','INDIA','500079',97401926342,'TESTINGTOOL')
INSERT INTO EMPLOYEE VALUES (5,'URIKESH','11-12-1979',62,'HYDERABAD','INDIA','500079',970192685342,'TESTINGKIRAN')

INSERT INTO ATTENDENCE VALUES ('07-18-2022',1,'A')
INSERT INTO ATTENDENCE VALUES('07-18-2022',2,'A')
INSERT INTO ATTENDENCE VALUES('07-18-2022',3,'A')
INSERT INTO ATTENDENCE VALUES('07-18-2022',4,'P')
INSERT INTO ATTENDENCE VALUES('07-18-2022',5,'P')

SELECT EMPNO FROM ATTENDENCE WHERE DATEPART(MM,A_DATE) = 7 AND A_STATUS= 'A'

SELECT DISTINCT A.E_NAME FROM EMPLOYEE A,ATTENDENCE B WHERE DATEPART(MONTH,B.A_DATE)= 7 AND B.A_STATUS= 'A' AND A.EMPNO = B.EMPNO


